USE [ISYS4283];
GO

IF OBJECT_ID('dbo.drop_users', 'p') IS NULL
    EXEC('CREATE PROCEDURE drop_users AS SELECT 1')
GO
ALTER PROCEDURE drop_users
AS
SET NOCOUNT ON
	DECLARE @login CHAR(11)
	DECLARE @query NVARCHAR(255)

	DECLARE MY_CURSOR CURSOR 
	  LOCAL STATIC READ_ONLY FORWARD_ONLY
	FOR 
	SELECT vendor 
	FROM logins

	OPEN MY_CURSOR
	FETCH NEXT FROM MY_CURSOR INTO @login
	WHILE @@FETCH_STATUS = 0
	BEGIN
	IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = @login)
		BEGIN
			SET @query = 'DROP USER ' + @login
			EXEC sp_executesql @query
		END
	FETCH NEXT FROM MY_CURSOR INTO @login
	END
	CLOSE MY_CURSOR
	DEALLOCATE MY_CURSOR

	IF DATABASE_PRINCIPAL_ID('ISYS4283vendors') IS NULL
		DROP ROLE ISYS4283vendors;

GO
